FROM node:20-alpine
RUN apk add --no-cache git bash
WORKDIR /app
COPY package.json ./
RUN rm -f package-lock.json && npm install
COPY . .
RUN npm run build
ENV HOST=0.0.0.0
ENV PORT=5173
ENV CHOKIDAR_USEPOLLING=true
COPY . .
EXPOSE 5173
CMD [ "npm", "run", "dev", "--", "--host" ]
